
#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_pick_rep_seq
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Align representative sequences"
align_seqs.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/rep_set.fna -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/pynast_aligned -t ~/2018_02_smb/97_alignment.fna
source deactivate
