#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Alpha rarefraction from OTU table"
alpha_rarefaction.py -o ~/2018_02_smb/Alpha_rarefraction_pick_/ -m 35000 -x 195000 -s 20000 -n 50 -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61/otu_table_no_singletons_abundance.biom
source deactivate
