
#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_collate_alpha
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Collate alpha diversity tables"
collate_alpha.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/adiv -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/collated_alpha
source deactivate
