#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_compare_categories
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Compare categories"
compare_categories.py --method bioenv -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/beta_diversity_through_plots/unweighted_unifrac_dm.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/statistics/beta_diversity_through_plots/bioenv_output -c VegetationSpecies,SamplePh,SamplePotassium,SampleNitrogen,SamplePhosphorus -m ~/Categorical_mapping_file.tsv
source deactivate
