#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_split_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Core diversity analysis"
core_diversity_analyses.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs/otu_table.biom -o ~/2018_02_smb/Core_Diversity_Analysis -m ~/"map - Sheet1.tsv" -t~/2018_02_smb/97_otus.tre  -c #SampleID,BarcodeSequence,LinkerPrimerSequence,SampleType,Year,Month,Day,SampleLongitude,SampleLatitude,SampleSiteDescription,SampleDepth,SampleFootFall,SampleVegetation,SampleWeatherTemp,SampleMoisture,SampleDescription,SamplePh,SamplePotassium,SampleNitrogen,SamplePhosphorus,Description -e 35000 -a -O 32 
source deactivate
