#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_chimeric_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Removing chimeric sequences"
filter_fasta.py -f ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/pynast_aligned/rep_set_aligned.fasta -s ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/chimeric_seqs_cs.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/rep_set_aligned_chimerafree.fasta
source deactivate
