#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_chimeric_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Removing chimeric sequences"
filter_fasta.py -f ~/git/Split_Libraries_25/seqs.fna -s ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/chimeric_seqs_usearch61/chimeras.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/seqs_chimeras_usearch61_filtered.fna -n
source deactivate
