#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_chimeric_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Identifying chimeric sequences"
filter_fasta.py -f pick_otus/pynast_aligned_seqs/rep_set_aligned.fasta -o pick_otus/pynast_aligned_seqs/rep_set_aligned_chimerafree.fasta -s pick_otus/chimeric_seqs.txt --negate
source deactivate
