#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_group_significance
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Group significance"
group_significance.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/otu_table_ids_removed_with_map_no_singletons.biom -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/statistics/group_significance_output -c VegetationSpecies -s nonparametric_t_test -m ~/Filtered_vegetation_map_file.tsv
source deactivate
