#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_chimeric_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Identifying chimeric sequences"
identify_chimeric_seqs.py -i ~/git/Split_Libraries_25/seqs.fna -o ~/2018_02_smb/Split_Libraries_25/identified_chimeraslayer.txt
source deactivate
