#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_chimeric_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Identifying chimeric sequences"
identify_chimeric_seqs.py -i ~/git/Split_Libraries_25/seqs.fna -r ~/2018_02_smb/silva_132_97_16S.fna -m usearch61 -o ~/2018_02_smb/Split_Libraries_25/identified_chimeras.txt -T -O 32
source deactivate
