#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_join_paired_ends
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
export TMPDIR=~/qiime_tmp
join_paired_ends.py \ 
-m SeqPrep \
-b /lustre/home/d411/patrosel/Index.fastq.gz \
-f /lustre/home/d411/patrosel/Read1.fastq.gz \
-r /lustre/home/d411/patrosel/Read2.fastq.gz \
-o /lustre/home/d411/patrosel/SeqPrep_joined
