#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_filter_outliers
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Make OTU table"
make_otu_table.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/Unfiltered_with_grass/seqs_chimeras_usearch61_filtered_sfiltered_otus.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/Unfiltered_with_grass/otu_table_ids_filtered_map_taxonomy_categorical.biom -t ~/2018_02_smb/consensus_taxonomy_7_levels.txt -m ~/2_Categorical_Unfiltered_vegetation_map_file.tsv
source deactivate
