#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_pick_rep_seq
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Align representative sequences"
make_phylogeny.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61/aligned.fasta -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61/rep_phylo.tre
source deactivate
