#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_make_rarefraction_plots
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Make rarefraction plots"
make_rarefaction_plots.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61/rarefied_otu_tables_32 -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61/parallel_adiv_32 -m observed_otus,chao1,PD_whole_tree,goods_coverage -t ~/2018_02_smb/97_otus.tre -O 32
source deactivate
