#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_tree
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "make 2d plots"
make_bootstrapped_tree.py -m ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/jackknifed_beta_diversity_2/unweighted_unifrac/upgma_cmp/master_tree.tre -s ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/jackknifed_beta_diversity_2/unweighted_unifrac/upgma_cmp/jackknife_support.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/jackknifed_beta_diversity_2/unweighted_unifrac/upgma_cmp/tree.pdf
source deactivate
