#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_parallel_alpha_diveristy
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Parallel alpha diversity"
parallel_alpha_diversity.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/rarefied_otu_tables -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25/adiv -m observed_otus,chao1,PD_whole_tree,goods_coverage -t ~/2018_02_smb97_otus.tre -O 32
source deactivate
