
#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_open_pick_otus
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Picking OTUs with open reference"
pick_open_reference_otus.py -i ~/git/Split_Libraries_19/seqs.fna -r ~/2018_02_smb/silva_132_97_16S.fna -s 0.1 --prefilter_percent_id 0.0 -o ~/2018_02_smb/Pick_Open_Reference_OTUs -a -O 32 
source deactivate
