

#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_split_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Picking representative sequence"
pick_rep_set.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs/uclust_ref_picked_otus/seqs_otus.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs/rep_set.fasta -f /lustre/home/d411/patrosel/2018_02_smb/silva_132_97_16S.fna -l ~/2018_02_smb/Pick_Closed_Reference_OTUs/rep_set_log.log -m most_abundant
source deactivate
