#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "Core diversity analysis"
plot_taxa_summary.py -i ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/summarize_taxa/Filtered_vegetation_map_file_L2.txt,~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/summarize_taxa/Filtered_vegetation_map_file_L3.txt,~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/summarize_taxa/Filtered_vegetation_map_file_L4.txt,~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/summarize_taxa/Filtered_vegetation_map_file_L5.txt,~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/summarize_taxa/Filtered_vegetation_map_file_L6.txt -o ~/2018_02_smb/Pick_Closed_Reference_OTUs_25_without_chimeras_usearch61_final/plot_taxa_summary -l Phylum,Class,Order,Family,Genus,Species -c pie,bar,chart -t png
source deactivate
