#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_split_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "splitting libraries"
split_libraries_fastq.py -i ~/2018_02_smb/SeqPrep_joined_2/seqprep_assembled.fastq.gz -b ~/2018_02_smb/SeqPrep_joined_2/seqprep_assembled.fastq_barcodes.fastq -o Split_Libraries_25 -m ~/"map - Sheet1.tsv" -q 25 --rev_comp_barcode --rev_comp_mapping_barcodes
source deactivate
