#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_split_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "splitting libraries"
split_libraries_fastq.py -i ~/2018_02_smb/SeqPrep_joined/fastqjoin.join.fastq -b ~/2018_02_smb/Index.fastq.gz -o slout -m ~/2018_02_smb/map_incomplete.tsv -q 19
source deactivate
